identifier_name:
    allowed_symbols: ["_"]
    validates_start_with_lowercase: false
    min_length:
        warning: 2
        
type_name:
    validates_start_with_lowercase: false
    
line_length:
  warning: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true

disabled_rules: # rule identifiers to exclude from running
    - colon
    - comma
    - control_statement
    - unused_optional_binding
    - opening_brace
    - trailing_whitespace
    - unneeded_break_in_switch
    - force_try

opt_in_rules: # some rules are only opt-in
    - empty_count
    - missing_docs
    # Find all the available rules by running:
    # swiftlint rules

included: # paths to include during linting. `--path` is ignored if present.
    - Source
    - findT

excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Pods
